/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test 
    void createACard() {
        Card nullCard = new Card();

        // Check if a default card has been created
        assertNotNull(nullCard);
        assertEquals("", nullCard.getQuestion());
        assertEquals("", nullCard.getAnswer());
    }

    @Test
    void createCardWithContent() {
        Card filledCard = new Card();
        filledCard.setQuestion("Whats 9 + 10");
        filledCard.setAnswer("21");

        assertNotNull(filledCard);
        assertEquals("Whats 9 + 10", filledCard.getQuestion());
        assertEquals("21", filledCard.getAnswer());
    }
}
